name = "e7-edgesub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "EdgeSubDB"
id = "9feac058c10347a6b0dc72909c569877"
